<a href="https://colab.research.google.com/github/Vyoma-garg/Natural-Language-Processing/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Word Embeddings**

**Taking 200 Documents for creating corpus**

In [ ]:
corpus=newsgroups_train.data[0:200]
type(corpus)
#corpus[:2]

list

### **(i)Word2Vec Embedding Matrix**

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
#X_data, y_data = corpus, bin_sentiment
X_data, y_data = np.array(newsgroups_train.target_names), np.array(newsgroups_train.target)
print(X_data)
print(y_data)

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, random_state = 40)
print('Data Split done.')
X_data.shape
y_data.shape

y_test.shape
type(X_train)
X_train.shape

In [ ]:
from gensim.models import Word2Vec, KeyedVectors
import pandas as pd
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
Embedding_dimensions = 100
Word2vec_train_data = list(map(lambda x: x.split(), corpus))
len(Word2vec_train_data)

200

In [ ]:
# Defining the model and training it.
word2vec_model = Word2Vec(Word2vec_train_data ,
                 size=Embedding_dimensions,
                 workers=8,
                 min_count=5)

print("Vocabulary Length:", len(word2vec_model.wv.vocab))

#word2vec_model.wv.vocab

Vocabulary Length: 1273


In [ ]:
input_length = 60

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
tokenizer = Tokenizer(filters="", lower=True)
tokenizer.fit_on_texts(corpus)

vocab_length = len(tokenizer.word_index) + 1
print("Tokenizer vocab length:", vocab_length)
lili=list(tokenizer.word_index)
#lili

Tokenizer vocab length: 16590


In [ ]:
tokenizer.word_index.items()

**WORD2VEC EMBEDDING MATRIX**

In [ ]:
import numpy as np
embedding_matrix = np.zeros((vocab_length, Embedding_dimensions))

for word, token in tokenizer.word_index.items():
    if word2vec_model.wv.__contains__(word):
        embedding_matrix[token] = word2vec_model.wv.__getitem__(word)

print("Embedding Matrix Shape:", embedding_matrix.shape)
embedding_matrix


Embedding Matrix Shape: (16590, 100)


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.09553948,  0.42800477,  1.15113389, ..., -0.55253488,
        -0.04539686,  0.2248902 ],
       [ 0.10282847,  0.41432583,  1.12297511, ..., -0.5347597 ,
        -0.05884048,  0.21773049],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

### **(ii)GLOVE embeddings**

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2021-05-04 10:40:50--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2021-05-04 10:40:51--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.04MB/s    in 2m 40s  

2021-05-04 10:43:31 (5.13 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [ ]:
!unzip glove*.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [ ]:
embeddings_index = dict()

f = open('/content/glove.6B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

**GLOVE EMBEDDING MATRIX**

In [ ]:
embedding_matrix_glove = np.zeros((vocab_length,100))
for word, i in tokenizer.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix_glove[i] = embedding_vector
print(embedding_matrix_glove.shape)
embedding_matrix_glove


(16590, 100)


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.038194  , -0.24487001,  0.72812003, ..., -0.1459    ,
         0.82779998,  0.27061999],
       [-0.1529    , -0.24279   ,  0.89837003, ..., -0.59100002,
         1.00390005,  0.20664001],
       ...,
       [-0.12134   ,  0.25116   , -0.28042001, ...,  0.44575   ,
        -0.10716   , -0.68197   ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

### **(iii)Fasttext Word Embeddings**

In [ ]:
# Defining values for parameters
embedding_size = 100
window_size = 5
min_word = 5
down_sampling = 1e-2
 
#%%time
fast_Text_model = FastText(Word2vec_train_data,
                      size=embedding_size,
                      window=window_size,
                      min_count=min_word,
                      sample=down_sampling,
                      workers = 4,
                      sg=1,
                      iter=100)

**FASTTEXT EMBEDDING MATRIX**

In [ ]:
import numpy as np
embedding_matrix_fasttext = np.zeros((vocab_length, Embedding_dimensions))

for word, token in tokenizer.word_index.items():
    if fast_Text_model.wv.__contains__(word):
       embedding_matrix_fasttext [token] = fast_Text_model.wv.__getitem__(word)

print("Embedding Matrix Shape:", embedding_matrix_fasttext .shape)
embedding_matrix_fasttext 


Embedding Matrix Shape: (16590, 100)


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.13058279,  0.30853915,  0.06052507, ..., -0.10447433,
         0.42034531,  0.22874126],
       [ 0.23419413,  0.05552264,  0.3274363 , ..., -0.32826954,
         0.34291354,  0.07401072],
       ...,
       [ 0.19601822,  0.55284888,  0.80247927, ..., -0.47504708,
         0.90072495,  0.13029887],
       [ 0.19215195,  0.01958453,  0.74994725, ...,  0.38403332,
        -0.06862366,  0.46224916],
       [ 0.09854463,  0.13877454,  0.98170364, ...,  0.13627307,
        -0.17717718,  0.43741387]])